### ISSUE TITLE
Failing to pass tests - Building with Turing architecture.

### ISSUE THREAD

**Issue by GregorySchwing** [mattsinc/heterosync#4]
Is this code supported for Turing gpu's; cuda 12?

nvidia-smi
Sat Sep  9 16:47:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|   0  Quadro RTX 5000...  Off  | 00000000:01:00.0 Off |                  N/A |

./allSyncPrims-1kernel spinMutex 1 1 1
GPU Compute Capability: 7.5
# SM: 48, Max Thrs/TB: 1024, Max TB/SM: 32, Max # TB: 1536
# TBs: 1, # Ld/St: 1, # Locs Mult: 1, # Uniq Locs/TB: 64, # Storage Locs: 64
spin_lock_mutex_001
Comparing GPU results to golden results:
        ERROR: storage[16] = 16.000000, golden[16] = 0.000000
        ERROR: storage[17] = 17.000000, golden[17] = 1.000000
        ERROR: storage[18] = 18.000000, golden[18] = 2.000000
        ERROR: storage[19] = 19.000000, golden[19] = 3.000000
        ERROR: storage[20] = 20.000000, golden[20] = 4.000000
        ERROR: storage[21] = 21.000000, golden[21] = 5.000000
        ERROR: storage[22] = 22.000000, golden[22] = 6.000000
        ERROR: storage[23] = 23.000000, golden[23] = 7.000000
        ERROR: storage[24] = 24.000000, golden[24] = 8.000000
        ERROR: storage[25] = 25.000000, golden[25] = 9.000000
        ERROR: storage[26] = 26.000000, golden[26] = 10.000000
        ERROR: storage[27] = 27.000000, golden[27] = 11.000000
        ERROR: storage[28] = 28.000000, golden[28] = 12.000000
        ERROR: storage[29] = 29.000000, golden[29] = 13.000000
        ERROR: storage[30] = 30.000000, golden[30] = 14.000000
        ERROR: storage[31] = 31.000000, golden[31] = 15.000000
        ERROR: storage[48] = 48.000000, golden[48] = 32.000000
        ERROR: storage[49] = 49.000000, golden[49] = 33.000000
        ERROR: storage[50] = 50.000000, golden[50] = 34.000000
        ERROR: storage[51] = 51.000000, golden[51] = 35.000000
        ERROR: storage[52] = 52.000000, golden[52] = 36.000000
        ERROR: storage[53] = 53.000000, golden[53] = 37.000000
        ERROR: storage[54] = 54.000000, golden[54] = 38.000000
        ERROR: storage[55] = 55.000000, golden[55] = 39.000000
        ERROR: storage[56] = 56.000000, golden[56] = 40.000000
        ERROR: storage[57] = 57.000000, golden[57] = 41.000000
        ERROR: storage[58] = 58.000000, golden[58] = 42.000000
        ERROR: storage[59] = 59.000000, golden[59] = 43.000000
        ERROR: storage[60] = 60.000000, golden[60] = 44.000000
        ERROR: storage[61] = 61.000000, golden[61] = 45.000000
        ERROR: storage[62] = 62.000000, golden[62] = 46.000000
        ERROR: storage[63] = 63.000000, golden[63] = 47.000000
ERROR: spinMutex has 32 output errors

**Comment by GregorySchwing** [comment]
Closing as I was trying to use the denovo build.  The uvm build works on my machine.

**Comment by mattsinc** [comment]
Sorry I didn't respond before you figured it out, but yes what you did is what I would have suggested!
